const $=s=>document.querySelector(s), modal=$('#modal'), panel=$('#panel');
const store={get:k=>localStorage.getItem(k)||'',set:(k,v)=>localStorage.setItem(k,v)};
// iPad app URL schemes. If iPadOS or an app does not accept a scheme, the official web fallback remains available in the panel.
function launchApp(scheme){window.location.href=scheme;}
function clock(){let d=new Date();$('#clock').textContent=d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});let h=d.getHours();$('#greeting').textContent=`Good ${h<12?'morning':h<18?'afternoon':'evening'}, Arnav.`}clock();setInterval(clock,10000);
function cfg(){return {url:store.get('ha_url').replace(/\/$/,''),token:store.get('ha_token')}}
async function ha(path,options={}){let c=cfg();if(!c.url||!c.token)throw Error('Home Assistant is not connected. Open Settings → Connect Home Assistant.');let r=await fetch(c.url+'/api/'+path,{...options,headers:{Authorization:'Bearer '+c.token,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw Error(r.status===401?'Connection refused: check your token.':`Home Assistant returned ${r.status}.`);return r.json()}
function esc(s){return String(s||'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
async function loadHome(){let target=$('.camgrid');if(!cfg().url){target.innerHTML='<button class="empty" onclick="ring()">Open Ring</button>';return}target.innerHTML='<div class="empty">Loading your Ring devices…</div>';try{let states=await ha('states');let cams=states.filter(x=>x.entity_id.startsWith('camera.')&&(x.attributes?.friendly_name||'').toLowerCase().match(/ring|doorbell|front|back|yard/)).slice(0,2);if(!cams.length){target.innerHTML='<div class="empty">No Ring camera entities found. Add Ring under Home Assistant → Settings → Devices & services.</div>';return}target.innerHTML=cams.map(x=>`<button class="feed realfeed" data-entity="${esc(x.entity_id)}"><span>${esc(x.attributes.friendly_name||x.entity_id)}</span><strong>◉</strong><small>${esc(x.state)}</small></button>`).join('');target.querySelectorAll('.realfeed').forEach(b=>b.onclick=()=>openCamera(b.dataset.entity));}catch(e){target.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function openCamera(entity){if(!cfg().url){ring();return}open('camera');panel.innerHTML='<p class="eyebrow">LIVE HOME · RING</p><h2>Camera</h2><p>Loading secure camera view…</p>';try{let c=cfg(), s=await ha('states/'+entity);let pic=s.attributes.entity_picture;if(pic){let image=await fetch(c.url+pic,{headers:{Authorization:'Bearer '+c.token}});if(!image.ok)throw Error('Camera image could not be retrieved.');let objectURL=URL.createObjectURL(await image.blob());panel.innerHTML=`<p class="eyebrow">LIVE HOME · RING</p><h2>${esc(s.attributes.friendly_name||entity)}</h2><img class="cameraimg" src="${objectURL}" alt="Camera image"><p>State: ${esc(s.state)}</p><p class="note">Camera image delivered by your Home Assistant instance.</p>`}else panel.innerHTML=`<h2>${esc(s.attributes.friendly_name||entity)}</h2><p>This Ring entity does not currently provide a camera image. Open it in Home Assistant for its supported live view.</p><a class="action" target="_blank" href="${c.url}/lovelace/0">Open Home Assistant ↗</a>`}catch(e){panel.innerHTML='<h2>Camera unavailable</h2><p>'+esc(e.message)+'</p>'}}
const basic={youtube:['YouTube','Launch the official YouTube app, or use its official web fallback.','https://m.youtube.com/','Open YouTube'],music:['Music','Launch the official YouTube Music app, or use its official web fallback.','https://music.youtube.com/','Open YouTube Music'],files:['Files','Open iCloud Drive in the browser, or use Apple Files on your iPad.','https://www.icloud.com/iclouddrive/','Open iCloud Drive'],assistant:['Kochar AI','Connect a secure AI backend before using this feature.','','']};
function open(name){if(name==='home'){modal.classList.remove('show');return}if(name==='settings'){settings();return}if(name==='camera'){if(!cfg().url){ring();return}openCameraList();return}if(name==='smart'){if(!cfg().url){alexa();return}devices();return}if(name==='assistant'){let p=basic.assistant;panel.innerHTML=`<p class="eyebrow">KOCHAR OS · AI</p><h2>${p[0]}</h2><p>${p[1]}</p>`;modal.classList.add('show');return}let p=basic[name]||basic.assistant;panel.innerHTML=`<p class="eyebrow">KOCHAR OS</p><h2>${p[0]}</h2><p>${p[1]}</p>${p[2]?`<a class="action" target="_blank" rel="noopener" href="${p[2]}">${p[3]} ↗</a>`:''}`;modal.classList.add('show')}
function settings(){panel.innerHTML=`<p class="eyebrow">SYSTEM SETTINGS</p><h2>Connect Home Assistant</h2><p>Kochar connects to your own Home Assistant, which securely connects to Ring and Alexa. Your token is kept only in this iPad browser storage.</p><label>Home Assistant URL<input id="haurl" class="aiinput" placeholder="https://homeassistant.local:8123" value="${esc(store.get('ha_url'))}"></label><label>Long-Lived Access Token<input id="hatoken" type="password" class="aiinput" placeholder="Paste token" value="${esc(store.get('ha_token'))}"></label><button class="action" id="saveha">Save & test connection</button><p id="result" class="note"></p><hr><h3>Alexa</h3><p>Set Alexa up inside Home Assistant first. Once it is linked, the same real devices shown here can be exposed to Alexa voice control.</p>`;modal.classList.add('show');$('#saveha').onclick=async()=>{store.set('ha_url',$('#haurl').value.trim());store.set('ha_token',$('#hatoken').value.trim());let r=$('#result');r.textContent='Testing…';try{let x=await ha('');r.textContent=x.message==='API running.'?'Connected to Home Assistant.':'Connected.';loadHome()}catch(e){r.textContent=e.message}}}
function ring(){panel.innerHTML='<p class="eyebrow">IPAD-ONLY MODE</p><h2>Ring</h2><p>Use the official Ring app for your real cameras, doorbells, events, and notifications.</p><button class="action" onclick="launchApp(\'ring://\')">Open Ring app</button><a class="action secondary" target="_blank" rel="noopener" href="https://ring.com/account/dashboard">Open Ring on web</a><p class="note">If the app button is not accepted by iPadOS, use the web link or open Ring from your Home Screen.</p>';modal.classList.add('show')}
function alexa(){panel.innerHTML='<p class="eyebrow">IPAD-ONLY MODE</p><h2>Alexa</h2><p>Use your signed-in official Alexa app for real Alexa devices, routines, and settings.</p><button class="action" onclick="launchApp(\'alexa://\')">Open Alexa app</button><a class="action secondary" target="_blank" rel="noopener" href="https://apps.apple.com/us/app/amazon-alexa/id944011620">Get Alexa</a><p class="note">If iPadOS does not open the app from this button, use the official App Store link. Integrated controls require a smart-home bridge later.</p>';modal.classList.add('show')}
async function devices(){panel.innerHTML='<p class="eyebrow">SMART HOME</p><h2>Your devices</h2><p>Loading…</p>';modal.classList.add('show');try{let ss=await ha('states');let items=ss.filter(x=>/^(light|switch|fan|cover)\./.test(x.entity_id)).slice(0,30);panel.innerHTML='<p class="eyebrow">SMART HOME</p><h2>Your devices</h2><div class="deviceList">'+items.map(x=>`<button class="device" data-e="${esc(x.entity_id)}"><span>${esc(x.attributes.friendly_name||x.entity_id)}</span><b>${esc(x.state)}</b></button>`).join('')+'</div>';panel.querySelectorAll('.device').forEach(b=>b.onclick=async()=>{try{let domain=b.dataset.e.split('.')[0], service=b.querySelector('b').textContent==='on'?'turn_off':'turn_on';await ha('services/'+domain+'/'+service,{method:'POST',body:JSON.stringify({entity_id:b.dataset.e})});devices()}catch(e){alert(e.message)}})}catch(e){panel.innerHTML='<h2>Devices unavailable</h2><p>'+esc(e.message)+'</p>'}}
async function openCameraList(){open('camera');panel.innerHTML='<p class="eyebrow">LIVE HOME · RING</p><h2>Ring cameras</h2><p>Loading…</p>';try{let ss=await ha('states'),cams=ss.filter(x=>x.entity_id.startsWith('camera.'));panel.innerHTML='<p class="eyebrow">LIVE HOME · RING</p><h2>Ring cameras</h2>'+cams.map(x=>`<button class="device cam" data-e="${esc(x.entity_id)}">${esc(x.attributes.friendly_name||x.entity_id)} <b>${esc(x.state)}</b></button>`).join('');panel.querySelectorAll('.cam').forEach(b=>b.onclick=()=>openCamera(b.dataset.e))}catch(e){panel.innerHTML='<h2>Ring cameras</h2><p>'+esc(e.message)+'</p>'}}
document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>open(x.dataset.open));$('#close').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};$('#searchBtn').onclick=()=>open('assistant');$('#play').onclick=e=>e.target.textContent=e.target.textContent==='▶'?'Ⅱ':'▶';if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');loadHome();